dist: xenial
services:
  - xvfb
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "lts/dubnium"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
addons:
  firefox: "latest"
cache: yarn
