language: node_js
node_js:
  - "node"
  - "lts/*"
  - "lts/carbon"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
addons:
  firefox: "latest"
cache: yarn
