name: Dependabot Automerge PR
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
    branches:
      - master
  check_suite:
    types:
      - completed
  status: {}

jobs:
  automerge:
    name: Dependabot Automerge
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    env:
      GITHUB_TOKEN: ${{ github.token }}
      MERGE_LABELS: "dependencies"
      MERGE_COMMIT_MESSAGE: "🔀 Automerge pull request #${{ github.event.pull_request.number }}"
    steps:
      - name: Automerge
        uses: pascalgn/automerge-action@v0.9.0
